### ISSUE TITLE
Question about checkpoints

### ISSUE THREAD

**Issue by CIawevy** [alex4727/InstantDrag#4]
Your work is fantastic, and I have tried your code. In the original paper, it was mentioned that in addition to pretraining on large face datasets, you also experimented with using LoRA fine-tuning on the SINTEL and FlyingChairs datasets to achieve general scene generalization. However, I couldn’t seem to find the fine-tuned checkpoints on Huggingface, and it appears that the part of the code that loads the weights does not include LoRA. I was wondering if you plan to open-source the fine-tuned weights and code in the future? Thank you!

**Comment by alex4727** [comment]
Please refer to your other issue (#5)!
